# -*- coding: utf-8 -*-
"""cog12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ATQHxV-hJgA2uB3cT-g2ynvETcZluIRA
"""

import re

class HealthBot:
    def __init__(self):
        self.responses = {
            r'hi|hello|hey': 'Hello! I am HealthBot. How can I assist you today?',
            r'headache': 'You should rest, stay hydrated, and take a mild pain reliever if needed.',
            r'fever': 'Drink plenty of fluids and rest. If the fever persists, please consult a doctor.',
            r'dizzy': 'Sit down, breathe deeply, and drink water. If it continues, seek medical help.',
            r'cold': 'Warm fluids, soups, citrus fruits, and light meals help during a cold.',
            r'stay healthy|healthy': 'Eat balanced meals, exercise regularly, stay hydrated, and get enough sleep.',
            r'cut': 'Clean the wound with water, apply antiseptic, and cover it with a clean bandage.',
            r'water|hydrate': 'Generally, 2 to 3 liters per day is recommended, but it varies based on your activity.',
            r'thank': 'You\'re welcome! Take care.',
            r'bye|goodbye': 'Goodbye! Stay healthy.'
        }

    def respond(self, user_input):
        user_input = user_input.lower().strip()

        for pattern, response in self.responses.items():
            if re.search(pattern, user_input):
                return response

        return "I'm not sure I understand. Could you rephrase your health concern?"

def main():
    bot = HealthBot()
    print("HealthBot: Hello! I am HealthBot. How can I assist you today?")

    while True:
        user_input = input("You: ")
        if user_input.lower() in ['quit', 'exit', 'bye']:
            print("HealthBot: Goodbye! Stay healthy.")
            break
        response = bot.respond(user_input)
        print(f"HealthBot: {response}")

if __name__ == "__main__":
    main()