# -*- coding: utf-8 -*-
"""cog10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f5OO8Q1twfCiGx8p25iemLkxRrNTXTEk
"""

import re
import nltk
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from collections import Counter
from wordcloud import WordCloud
import matplotlib.pyplot as plt
from textblob import TextBlob
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
import numpy as np

# Download NLTK resources with error handling
try:
    nltk.data.find('tokenizers/punkt')
except LookupError:
    nltk.download('punkt')

try:
    nltk.data.find('corpora/stopwords')
except LookupError:
    nltk.download('stopwords')

try:
    nltk.data.find('corpora/wordnet')
except LookupError:
    nltk.download('wordnet')

paragraph = """Quantum computing represents a revolutionary leap in processing power. These advanced machines leverage qubits to perform calculations exponentially faster than classical computers.
Major tech companies are investing billions in quantum research. Applications range from drug discovery to climate modeling and cryptography.
The field still faces challenges like quantum decoherence and error correction. However, breakthroughs are happening at an unprecedented pace."""

clean_text = re.sub(r'[^\w\s]', '', paragraph.lower())
words_split = clean_text.split()

try:
    words_nltk = word_tokenize(clean_text)
    sentences = sent_tokenize(paragraph)  # Use original paragraph for better sentence splitting
except LookupError:
    nltk.download('punkt')
    words_nltk = word_tokenize(clean_text)
    sentences = sent_tokenize(paragraph)

print("Python split:", words_split)
print("NLTK word_tokenize:", words_nltk)

stop_words = set(stopwords.words('english'))
filtered_words = [word for word in words_nltk if word not in stop_words]
freq = Counter(filtered_words)
print("Word Frequency (without stopwords):", freq)

alpha_words = re.findall(r'\b[a-zA-Z]+\b', clean_text)
filtered_alpha = [word for word in alpha_words if word not in stop_words]

stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()
stemmed = [stemmer.stem(word) for word in filtered_alpha]
lemmatized = [lemmatizer.lemmatize(word) for word in filtered_alpha]

print("\nStemmed:", stemmed)
print("Lemmatized:", lemmatized)

texts = [
    "Quantum computers use qubits instead of binary bits.",
    "Superconducting circuits are currently the leading quantum technology.",
    "Quantum algorithms can solve certain problems much faster than classical ones."
]

cv = CountVectorizer()
bow = cv.fit_transform(texts)
print("\nBag of Words:", bow.toarray())

tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(texts)
feature_names = tfidf.get_feature_names_out()

for i, text_vector in enumerate(tfidf_matrix):
    scores = zip(feature_names, text_vector.toarray()[0])
    sorted_scores = sorted(scores, key=lambda x: x[1], reverse=True)
    top_keywords = [word for word, score in sorted_scores[:3]]
    print(f"Text {i+1} Top 3 Keywords:", top_keywords)

text1 = """Quantum supremacy refers to a quantum computer solving a problem no classical computer could solve in reasonable time."""
text2 = """Error correction remains the biggest challenge for practical quantum computing applications."""

def preprocess(text):
    return set(re.sub(r'[^\w\s]', '', text.lower()).split())

set1, set2 = preprocess(text1), preprocess(text2)
jaccard = len(set1.intersection(set2)) / len(set1.union(set2))
print("\nJaccard Similarity:", jaccard)

vectorizer = TfidfVectorizer()
vectors = vectorizer.fit_transform([text1, text2])
cos_sim = cosine_similarity(vectors[0:1], vectors[1:2])[0][0]
print("Cosine Similarity:", cos_sim)

review = "The quantum processor demonstrates impressive coherence times but requires extremely cold operating temperatures."
blob = TextBlob(review)
print("\nSentiment Polarity:", blob.sentiment.polarity)
print("Subjectivity:", blob.sentiment.subjectivity)

if blob.sentiment.polarity > 0:
    sentiment = "Positive"
elif blob.sentiment.polarity < 0:
    sentiment = "Negative"
else:
    sentiment = "Neutral"
print("Review Sentiment:", sentiment)

quantum_terms = "Qubit Superposition Entanglement Decoherence Algorithm Qubit Gate Superposition"
wordcloud = WordCloud(background_color='white').generate(quantum_terms)
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.show()

train_text = """Quantum superposition allows qubits to exist in multiple states simultaneously. Quantum entanglement enables particles to remain connected across large distances. These phenomena form the basis of quantum computing power."""

tokenizer = Tokenizer()
tokenizer.fit_on_texts([train_text])
sequences = []
total_words = len(tokenizer.word_index) + 1
token_list = tokenizer.texts_to_sequences([train_text])[0]

for i in range(1, len(token_list)):
    sequences.append(token_list[:i+1])

sequences = np.array(sequences)
X, y = sequences[:,:-1], sequences[:,-1]
y = np.eye(total_words)[y]

model = Sequential([
    Embedding(total_words, 10, input_length=X.shape[1]),
    LSTM(50),
    Dense(total_words, activation='softmax')
])

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=500, verbose=0)

seed_text = "Quantum superposition"
next_words = 3

for _ in range(next_words):
    token_list = tokenizer.texts_to_sequences([seed_text])[0]
    token_list = np.pad(token_list, (X.shape[1] - len(token_list), 0), 'constant')
    predicted = np.argmax(model.predict(token_list.reshape(1, -1), axis=-1))
    for word, index in tokenizer.word_index.items():
        if index == predicted:
            seed_text += " " + word
            break

print("\nGenerated Text:", seed_text)